---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gowon-config
  labels:
    gowon/enabled: "true"
data:
  config.yaml: |
    commands:
      - command: cap
        endpoint: http://module1:8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gowon-config2
  labels:
    gowon/enabled: "true"
data:
  config2.yaml: |
    commands:
      - command: rev
        endpoint: http://module2:8080

      - command: cyan
        endpoint: http://module3:8080

      - command: regextest
        endpoint: http://module4:8080
        regex: '.*hello.*'
        help: |
          hello more like goodbye
          some more help here
          and some more
