---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gowon-config
data:
  config.yaml: |
    commands:
      - command: cap
        endpoint: http://module1:8080/message
        help: capitalise message
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gowon-config2
data:
  config2.yaml: |
    commands:
      - command: rev
        endpoint: http://module2:8080/message
        help: reverse text

      - command: cyan
        endpoint: http://module3:8080/message
        help: make text cyan

      - command: regextest
        endpoint: http://module4:8080/message
        regex: '.*hello.*'
        help: hello more like goodbye
