---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gowon-config
data:
  config.yaml: |
    commands:
      - command: cyan
        endpoint: http://module4:8080/message
        help: make text cyan
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gowon-config2
data:
  config2.yaml: |
    commands:
      - command: rev
        endpoint: http://module5:8080
        help: reverse text

      - command: regextest
        endpoint: http://module6:8080
        regex: '.*goodbye.*'
        help: hello more like goodbye
