---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.27.3-standalone-strict/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowon
  labels:
    app.kubernetes.io/name: gowon
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gowon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gowon
    spec:
      serviceAccountName: gowon
      initContainers:
        - name: init-config-sync
          image: ghcr.io/kiwigrid/k8s-sidecar:1.25.3
          env:
            - name: FOLDER
              value: /config
            - name: LABEL
              value: gowon/enabled
            - name: METHOD
              value: LIST
            - name: UNIQUE_FILENAMES
              value: "true"
            - name: LOG_LEVEL
              value: DEBUG
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: gowon
          image: gowon
          env:
            - name: GOWON_SERVER
              value: oragono:6667
            - name: GOWON_BROKER
              value: mosquitto:1883
            - name: GOWON_NICK
              value: gowon
            - name: GOWON_USER
              value: gowon
            - name: GOWON_CHANNELS
              value: "#gowon,#gowon2"
            - name: GOWON_CONFIG_DIR
              value: /config
          volumeMounts:
            - name: config
              mountPath: /config
          ports:
            - containerPort: 8080
              name: http
        - name: config-sync
          image: ghcr.io/kiwigrid/k8s-sidecar:1.25.3
          env:
            - name: FOLDER
              value: /config/source
            - name: LABEL
              value: gowon/enabled
            - name: METHOD
              value: WATCH
            - name: UNIQUE_FILENAMES
              value: "true"
            - name: LOG_LEVEL
              value: DEBUG
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
