---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module3
  labels:
    app.kubernetes.io/name: module3
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: module3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: module3
    spec:
      containers:
        - name: module3
          image: module3
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
