---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowon
  labels:
    app.kubernetes.io/name: gowon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gowon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gowon
    spec:
      containers:
        - name: gowon
          image: gowon
          env:
            - name: GOWON_SERVER
              value: oragono:6667
            - name: GOWON_BROKER
              value: mosquitto:1883
            - name: GOWON_NICK
              value: gowon
            - name: GOWON_USER
              value: gowon
            - name: GOWON_CHANNELS
              value: "#gowon,#gowon2"
            - name: GOWON_FILTERS
              value: "!module=module3+command=cap"
          ports:
            - containerPort: 8080
              name: http
