---
version: "3.6"

services:
  ircd:
    image: oragono/oragono
    container_name: ircd
    ports:
      - 6667:6667

  compiledaemon:
    image: klumhru/compiledaemon
    container_name: compiler
    entrypoint: >
      CompileDaemon
      -build="go build -o /gowon"
      -directory="/repo"
      -exclude-dir=".git"
      -command="/gowon"
    volumes:
      - ../:/repo
    environment:
      GOWON_SERVER: ircd:6667
      GOWON_NICK: gowon
      GOWON_USER: gowon
      GOWON_CHANNELS: "#gowon,#gowon2"
    ports:
      - 1337:1337
