---
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: gowon
      context: ./..
      docker:
        dockerfile: Dockerfile
    - image: module1
      context: module1
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - "kube/*"
