---
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: gowon
      context: ./..
      docker:
        dockerfile: Dockerfile
    - image: module1
      context: module1
      docker:
        dockerfile: Dockerfile
    - image: module2
      context: module2
      docker:
        dockerfile: Dockerfile
    - image: module3
      context: module3
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - "kube/*"
