---
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: gowon
      context: ./..
      ko:
        dependencies:
          paths:
            - "*.go"
          ignore:
            - "*_test.go"
    - image: module1
      context: module1
      ko:
        dependencies:
          paths:
            - "*.go"
          ignore:
            - "*_test.go"
    # - image: module2
    #   context: module2
    #   docker:
    #     dockerfile: Dockerfile
    - image: module3
      context: module3
      ko:
        dependencies:
          paths:
            - "*.go"
          ignore:
            - "*_test.go"
    - image: module4
      context: module4
      ko:
        dependencies:
          paths:
            - "*.go"
          ignore:
            - "*_test.go"
    - image: module5
      context: module5
      ko:
        dependencies:
          paths:
            - "*.go"
          ignore:
            - "*_test.go"
deploy:
  kubectl:
    manifests:
      - "kube/*"
