---
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: gowon
      context: ./..
      docker:
        dockerfile: Dockerfile
    - image: module1
      context: ./..
      docker:
        dockerfile: demo/module1/Dockerfile
    - image: module2
      context: module2
      docker:
        dockerfile: Dockerfile
    - image: module3
      context: ./..
      docker:
        dockerfile: demo/module3/Dockerfile
    - image: tiny
      context: .
      docker:
        dockerfile: tiny.Dockerfile
deploy:
  kubectl:
    manifests:
      - "kube/*"
